version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/common"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/composer/helpers/v1"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/composer/helpers/v2"
    schedule:
      interval: "daily"
  - package-ecosystem: "mix"
    directory: "/hex/helpers"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/npm_and_yarn/helpers"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "npm"
        # We explicitly need npm 6 here, in order to support npm 6.
        versions: ["version-update:semver-major"]
  - package-ecosystem: "pip"
    directory: "/python/helpers"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/go_modules/helpers"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
