AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/**/*
    - bin/**/*
    - tmp/**/*

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 80

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - dependabot-core.gemspec

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%I': ()
    '%w': ()
    '%W': ()
