version: 2
jobs:
  test:
    docker:
      - image: dependabot/dependabot-core:0.1.44
    working_directory: ~/dependabot-core
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies-master

      # Install dependencies
      - run: bundle install --path vendor/bundle
      - run: cd helpers/yarn && yarn install
      - run: cd helpers/npm && yarn install
      - run: cd helpers/php && composer install
      - run: cd helpers/python && pyenv exec pip install -r requirements.txt && pyenv local 2.7.15 && pyenv exec pip install -r requirements.txt && pyenv local --unset
      - run: cd helpers/elixir && mix deps.get
      - run: cd helpers/go && make

      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/dependabot-core/vendor/bundle
            - ~/dependabot-core/helpers/yarn/node_modules
            - ~/dependabot-core/helpers/npm/node_modules
            - ~/dependabot-core/helpers/php/vendor

      # Run code formatting linters
      - run: bundle exec rubocop
      - run: cd helpers/yarn && node_modules/.bin/eslint lib test bin
      - run: cd helpers/npm && node_modules/.bin/eslint lib test bin
      - run: cd helpers/php && vendor/bin/php-cs-fixer fix --dry-run

      # Run tests
      - run: cd helpers/yarn && node_modules/.bin/jest
      - run: cd helpers/npm && node_modules/.bin/jest
      - run: bundle exec rspec spec --format documentation --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - store_test_results:
          path: ~/rspec

workflows:
  version: 2
  test:
    jobs:
      - test
