inherit_from:
  - rubocop-default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'terraform/**/*'
    - 'elm/**/*'
    - 'docker/**/*'
    - 'git_submodules/**/*'
    - 'nuget/**/*'
    - 'python/**/*'
    - 'cargo/**/*'
