name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - "CHANGELOG.md"
      - "common/lib/dependabot/version.rb"
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: bundler, name: bundler1, ci_node_total: 2, ci_node_index: 0 }
          - { path: bundler, name: bundler1, ci_node_total: 2, ci_node_index: 1 }
          - { path: bundler, name: bundler2, ci_node_total: 2, ci_node_index: 0 }
          - { path: bundler, name: bundler2, ci_node_total: 2, ci_node_index: 1 }
          - { path: cargo, name: cargo }
          - { path: common, name: common }
          - { path: composer, name: composer, ci_node_total: 2, ci_node_index: 0 }
          - { path: composer, name: composer, ci_node_total: 2, ci_node_index: 1 }
          - { path: docker, name: docker }
          - { path: elm, name: elm }
          - { path: git_submodules, name: git_submodules }
          - { path: github_actions, name: github_actions }
          - { path: go_modules, name: go_module, ci_node_total: 2, index: 0 }
          - { path: go_modules, name: go_module, ci_node_total: 2, index: 1 }
          - { path: gradle, name: gradle }
          - { path: hex, name: hex, ci_node_total: 2, ci_node_index: 0 }
          - { path: hex, name: hex, ci_node_total: 2, ci_node_index: 1 }
          - { path: maven, name: maven }
          - { path: npm_and_yarn, name: npm_and_yarn, ci_node_total: 3, ci_node_index: 0 }
          - { path: npm_and_yarn, name: npm_and_yarn, ci_node_total: 3, ci_node_index: 1 }
          - { path: npm_and_yarn, name: npm_and_yarn, ci_node_total: 3, ci_node_index: 2 }
          - { path: nuget, name: nuget }
          - { path: omnibus, name: omnibus }
          - { path: python, name: python, ci_node_total: 5, ci_node_index: 0 }
          - { path: python, name: python, ci_node_total: 5, ci_node_index: 1 }
          - { path: python, name: python, ci_node_total: 5, ci_node_index: 2 }
          - { path: python, name: python, ci_node_total: 5, ci_node_index: 3 }
          - { path: python, name: python, ci_node_total: 5, ci_node_index: 4 }
          - { path: python, name: python_slow, ci_node_total: 5, ci_node_index: 0 }
          - { path: python, name: python_slow, ci_node_total: 5, ci_node_index: 1 }
          - { path: python, name: python_slow, ci_node_total: 5, ci_node_index: 2 }
          - { path: python, name: python_slow, ci_node_total: 5, ci_node_index: 3 }
          - { path: python, name: python_slow, ci_node_total: 5, ci_node_index: 4 }
          - { path: pub, name: pub, ci_node_total: 2, ci_node_index: 0 }
          - { path: pub, name: pub, ci_node_total: 2, ci_node_index: 1 }
          - { path: terraform, name: terraform }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build dependabot-core image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "dependabot/dependabot-core:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-core \
            .
      - name: Build dependabot-core-ci image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -f Dockerfile.ci \
            -t "dependabot-core-ci:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
      - name: Run ${{ matrix.suite.name }} tests
        run: |
          docker run \
            --env "CI=true" \
            --env "RAISE_ON_WARNINGS=true" \
            --env "DEPENDABOT_TEST_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            --env "SUITE_NAME=${{ matrix.suite.name }}" \
            --env "CI_NODE_TOTAL=${{ matrix.suite.ci_node_total }}" \
            --env "CI_NODE_INDEX=${{ matrix.suite.ci_node_index }}" \
            --rm dependabot-core-ci bash -c \
            "cd /home/dependabot/dependabot-core/${{ matrix.suite.path }} && ./script/ci-test"

  updater:
    name: Updater
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build dependabot-core image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "dependabot/dependabot-core:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-core \
            .
      - name: Free up disk space
        run: |
          sudo apt autoremove --purge && sudo apt -y clean
          docker system prune -af --volumes
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
      - name: GPR login
        run: docker login docker.pkg.github.com -u x -p ${{secrets.GITHUB_TOKEN}}
      - name: GHCR login
        run: docker login ghcr.io -u x -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: script/build
      - name: Lint
        run: script/lint
        env:
          SKIP_BUILD: true
      - name: Run updater tests
        run: ./script/ci-test-updater
        env:
          SKIP_BUILD: true
          DEPENDABOT_TEST_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./bin/lint
