name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - "CHANGELOG.md"
      - "common/lib/dependabot/version.rb"
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: bundler, name: bundler1 }
          - { path: bundler, name: bundler2 }
          - { path: cargo, name: cargo }
          - { path: common, name: common }
          - { path: composer, name: composer }
          - { path: docker, name: docker }
          - { path: elm, name: elm }
          - { path: git_submodules, name: git_submodules }
          - { path: github_actions, name: github_actions }
          - { path: go_modules, name: go_modules }
          - { path: gradle, name: gradle }
          - { path: hex, name: hex }
          - { path: maven, name: maven }
          - { path: npm_and_yarn, name: npm_and_yarn }
          - { path: nuget, name: nuget }
          - { path: omnibus, name: omnibus }
          - { path: python, name: python }
          - { path: python, name: python_slow }
          - { path: pub, name: pub }
          - { path: terraform, name: terraform }
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build dependabot-core-ci image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -f Dockerfile.ci \
            -t "dependabot-core-ci:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-core \
            .
      - name: Run ${{ matrix.suite.name }} tests
        run: |
          docker run \
            --env "CI=true" \
            --env "RAISE_ON_WARNINGS=true" \
            --env "DEPENDABOT_TEST_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            --env "SUITE_NAME=${{ matrix.suite.name }}" \
            --rm dependabot-core-ci bash -c \
            "cd /home/dependabot/dependabot-core/${{ matrix.suite.path }} && ./script/ci-test"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./bin/lint
        continue-on-error: true
