name: Push docker images
on:
  push:
    branches:
    - '*'
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  push-core-image:
    name: Push dependabot-core image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull Docker base image & warm Docker cache
        run: |
          docker pull "dependabot/dependabot-core:latest"
      - name: Build dependabot-core image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo "lol1"
      - name: Push image to packages (latest)
        if: '!contains(github.ref, "refs/tags")'
        run: |
          echo "lol2"
      - name: Push image to packages (tagged)
        if: contains(github.ref, "refs/tags")
        run: |
          echo "lol3"

