name: CI-Eco
on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: bundler, name: bundler1, ci_node_total: 2, ci_node_index: 0, ecosystem: bundler }
          - { path: bundler, name: bundler1, ci_node_total: 2, ci_node_index: 1, ecosystem: bundler }
          - { path: bundler, name: bundler2, ci_node_total: 2, ci_node_index: 0, ecosystem: bundler }
          - { path: bundler, name: bundler2, ci_node_total: 2, ci_node_index: 1, ecosystem: bundler }
          - { path: cargo, name: cargo, ecosystem: cargo }
          - { path: common, name: common, ecosystem: common}
          - { path: composer, name: composer, ci_node_total: 2, ci_node_index: 0, ecosystem: composer }
          - { path: composer, name: composer, ci_node_total: 2, ci_node_index: 1, ecosystem: composer }
          - { path: docker, name: docker, ecosystem: docker }
          - { path: elm, name: elm, ecosystem: elm }
          - { path: git_submodules, name: git_submodules, ecosystem: submodule }
          - { path: github_actions, name: github_actions, ecosystem: github-actions }
          - { path: go_modules, name: go_module, ci_node_total: 2, ci_node_index: 0, ecosystem: gomod }
          - { path: go_modules, name: go_module, ci_node_total: 2, ci_node_index: 1, ecosystem: gomod }
          - { path: gradle, name: gradle, ecosystem: gradle }
          - { path: hex, name: hex, ci_node_total: 2, ci_node_index: 0, ecosystem: hex }
          - { path: hex, name: hex, ci_node_total: 2, ci_node_index: 1, ecosystem: hex }
          - { path: maven, name: maven, ecosystem: maven }
          - { path: npm_and_yarn, name: npm_and_yarn, ci_node_total: 3, ci_node_index: 0, ecosystem: npm }
          - { path: npm_and_yarn, name: npm_and_yarn, ci_node_total: 3, ci_node_index: 1, ecosystem: npm }
          - { path: npm_and_yarn, name: npm_and_yarn, ci_node_total: 3, ci_node_index: 2, ecosystem: npm }
          - { path: nuget, name: nuget, ecosystem: nuget }
          - { path: pub, name: pub, ci_node_total: 2, ci_node_index: 0, ecosystem: pub }
          - { path: pub, name: pub, ci_node_total: 2, ci_node_index: 1, ecosystem: pub }
          - { path: python, name: python, ci_node_total: 2, ci_node_index: 0, ecosystem: pip }
          - { path: python, name: python, ci_node_total: 2, ci_node_index: 1, ecosystem: pip}
          - { path: python, name: python_slow, ci_node_total: 2, ci_node_index: 0, ecosystem: pip }
          - { path: python, name: python_slow, ci_node_total: 2, ci_node_index: 1, ecosystem: pip }
          - { path: terraform, name: terraform, ecosystem: terraform }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            bundler:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'bundler/**'
            cargo:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'cargo/**'
            common:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
            composer:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'composer/**'
            docker:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'docker/**'
            elm:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'elm/**'
            git_submodules:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'git_submodules/**'
            github_actions:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'github_actions/**'
            go_modules:
              - Dockerfile.updater-core
              - 'common/**'
              - 'go_modules/**'
              - '.github/workflows/ecosystem-ci.yml'
            gradle:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'maven/**'
              - 'gradle/**'
            hex:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'hex/**'
            maven:
              - Dockerfile.updater-core
              - 'common/**'
              - 'maven/**'
              - '.github/workflows/ecosystem-ci.yml'
            npm_and_yarn:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'npm_and_yarn/**'
            nuget:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'nuget/**'
            pub:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - '.github/workflows/ecosystem-ci.yml'
              - 'pub/**'
            python:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - 'python/**'
              - '.github/workflows/ecosystem-ci.yml'
            terraform:
              - Dockerfile.updater-core
              - 'common/**'
              - 'omnibus/**'
              - 'terraform/**'
              - '.github/workflows/ecosystem-ci.yml'

      - name: Build updater core image
        if: steps.changes.outputs[matrix.suite.path] == 'true'
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "ghcr.io/dependabot/dependabot-updater-core:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-updater-core \
            -f Dockerfile.updater-core \
            .

      - name: Build ecosystem image
        if: steps.changes.outputs[matrix.suite.path] == 'true'
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "dependabot/dependabot-updater-${{ matrix.suite.ecosystem }}:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-updater-${{ matrix.suite.ecosystem }} \
            -f ${{ matrix.suite.path }}/Dockerfile \
            .

      - name: Run ${{ matrix.suite.name }} tests
        if: steps.changes.outputs[matrix.suite.path] == 'true'
        run: |
          docker run \
            --env "CI=true" \
            --env "RAISE_ON_WARNINGS=true" \
            --env "DEPENDABOT_TEST_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            --env "SUITE_NAME=${{ matrix.suite.name }}" \
            --env "CI_NODE_TOTAL=${{ matrix.suite.ci_node_total }}" \
            --env "CI_NODE_INDEX=${{ matrix.suite.ci_node_index }}" \
            --rm dependabot/dependabot-updater-${{ matrix.suite.ecosystem }} bash -c \
            "cd /home/dependabot/${{ matrix.suite.path }} && ./script/ci-test"

  updater:
    env:
      DOCKER_BUILDKIT: 1
    name: Updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build updater core image
        run: |
          docker build \
            -t "ghcr.io/dependabot/dependabot-updater-core:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-updater-core \
            -f Dockerfile.updater-core \
            .
      # using bundler as the test updater
      - name: Build ecosystem image
        run: |
          docker build \
            -t "dependabot/dependabot-updater-bundler:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-updater-bundler \
            -f bundler/Dockerfile \
            .
      - name: Run updater tests
        env:
          DEPENDABOT_TEST_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --env DEPENDABOT_TEST_ACCESS_TOKEN \
            --env VCR \
            --rm \
            -v "$(pwd)/updater/spec/fixtures/vcr_cassettes:/home/dependabot/dependabot-updater/spec/fixtures/vcr_cassettes" \
            -v "$(pwd)/npm_and_yarn:/home/dependabot/npm_and_yarn" \
            -v "$(pwd)/go_modules:/home/dependabot/go_modules" \
            -v "$(pwd)/composer:/home/dependabot/composer" \
            "dependabot/dependabot-updater-bundler:latest" bundle exec rspec

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: ./bin/lint
