# Runs all ecosystems cached and concurrently.
name: Smoke

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - docs/**
      - README.md
env:
  GH_TOKEN: ${{ secrets.E2E_PAT }}
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - actions
          - bundler
          - cargo
          - composer
          - docker
          - elm
          - go
          - gradle
          - hex
          - maven
          - npm
          - nuget
          - pip
          - pip-compile
          - pipenv
          - poetry
          - pub
          - submodules
          - terraform
    steps:
    - uses: actions/checkout@v3

    - name: Download CLI and test
      run: |
        gh release download --repo dependabot/cli -p "*linux-amd64.tar.gz"
        tar xzvf *.tar.gz >/dev/null 2>&1
        ./dependabot --version
        URL=https://api.github.com/repos/dependabot/cli/contents/testdata/smoke-${{ matrix.suite }}.yaml
        curl $(gh api $URL --jq .download_url) -o smoke.yaml

    # Download the Proxy cache. The job is ideally 100% cached so no real calls are made.
    - name: Download cache
      run: |
        mkdir cache
        cd cache
        gh run download --repo dependabot/cli --name cache-${{ matrix.suite }}

    - name: GPR login
      run: docker login docker.pkg.github.com -u x -p ${{secrets.GITHUB_TOKEN}}
    - name: GHCR login
      run: docker login ghcr.io -u x -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build dependabot-core image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build \
          -t "dependabot/dependabot-core:latest" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from ghcr.io/dependabot/dependabot-core \
          .
    - name: Build dependabot-updater image
      env:
        DOCKER_BUILDKIT: 1
        OMNIBUS_VERSION: latest
      run: |
        docker build \
          -t "dependabot/updater:latest" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from ghcr.io/dependabot/dependabot-core \
          --cache-from ghcr.io/dependabot/dependabot-updater/dependabot-updater \
          --build-arg OMNIBUS_VERSION=$OMNIBUS_VERSION \
          -f Dockerfile.updater \
          .

    - name: ${{ matrix.suite }}
      env:
        LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.E2E_PAT }}
      run: |
        set -o pipefail
        ./dependabot test -f=smoke.yaml -o=result.yaml --cache=cache --timeout=20m --updater-image=dependabot/updater:latest 2>&1 | tee -a log.txt

    - name: Diff
      if: always()
      continue-on-error: true
      run: diff --ignore-space-change smoke.yaml result.yaml && echo "Contents are identical"

    - name: Create summary
      run: tail -n100 log.txt | grep -P '\d+/\d+ calls cached \(\d+%\)' >> $GITHUB_STEP_SUMMARY

    # No upload at the end:
    # - If a test is uncachable in some regard, the cache would grow unbound.
    # - We might want to consider erroring if the cache is changed.
