name: Sorbet
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sorbet:
    name: Sorbet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: ruby/setup-ruby@1d0e911f615a112e322369596f10ee0b95b010ae # v1.183.0
        with:
          bundler-cache: true

      - run: bundle exec tapioca gem --verify

      - run: bundle exec srb tc

      - run: bundle exec spoom srb coverage

      - run: |
          bundle exec spoom srb bump --from=false --to=true --dry
          bundle exec spoom srb bump --from=true --to=strict --dry
          bundle exec spoom srb bump --from=strict --to=strong --dry

      - run: bundle exec spoom srb coverage snapshot --save

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: spoom_data
          path: ./spoom_data/

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ./script/generate-coverage-report
        env:
          GH_TOKEN: ${{ github.token }}

      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: spoom_report
          path: ./spoom_report.html
